# Generated by Django 4.1 on 2022-09-06 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 16, 23, 12, 899525))),
            ],
        ),
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 16, 23, 12, 899525))),
                ('account_balance', models.FloatField(default=5.0)),
                ('total_profit', models.FloatField(default=0.0)),
                ('total_bonus', models.FloatField(default=0.0)),
                ('total_referral_bonus', models.FloatField(default=0.0)),
                ('total_investment_plans', models.FloatField(default=0.0)),
                ('total_active_investment_plans', models.FloatField(default=0.0)),
                ('total_deposit', models.FloatField(default=0.0)),
                ('total_withdrawals', models.FloatField(default=0.0)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('referral_id', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(default=datetime.datetime(2022, 9, 6, 15, 23, 12, 899525, tzinfo=datetime.timezone.utc))),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.IntegerField(blank=True)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.IntegerField(blank=True)),
                ('btc', models.CharField(blank=True, max_length=1000)),
                ('eth', models.CharField(blank=True, max_length=1000)),
                ('ltc', models.CharField(blank=True, max_length=1000)),
                ('otp', models.CharField(blank=True, max_length=4)),
                ('mail_profit', models.CharField(blank=True, max_length=4)),
                ('mail_expires', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 16, 23, 12, 915149))),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 16, 23, 12, 899525))),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('recieving_mode', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 16, 23, 12, 899525))),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('amount_requested', models.IntegerField()),
                ('amount_charges', models.CharField(max_length=100)),
                ('recieving_mode', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 16, 23, 12, 915149))),
            ],
        ),
    ]
